#
# DigitalOcean App Platform - Hot Reload Dev Environment
# Pre-built Node.js Image (Deploys in ~1 minute!)
#
# Usage:
#   doctl apps create --spec .do/app-hot-reload.yaml
#
# This configuration is for the sea-notes-saas-starter-kit application
# configured to use the hot-reload-dev branch with monorepo structure
#

name: sea-notes-hot-reload-dev-2
region: syd1

services:
  - name: dev-workspace
    # Pre-built image from GitHub Container Registry
    # No build phase = deploy in ~1 minute!
    image:
      registry_type: GHCR
      registry: bikramkgupta
      repository: hot-reload-node
      tag: latest

    instance_count: 1
    # Use 2GB instance for faster npm install (this app has many dependencies)
    instance_size_slug: apps-s-1vcpu-2gb

    # Application port (public HTTP traffic)
    http_port: 8080
    
    # Internal port for dev-health-server (used for health checks)
    internal_ports:
      - 9090

    # Health check configuration
    # Use the dev-health-server on port 9090 which stays running throughout
    # npm install and app startup. This ensures container health during the
    # potentially long npm install phase (puppeteer downloads Chromium).
    health_check:
      # Use the persistent dev-health-server endpoint (stays running always)
      http_path: /dev_health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      # Use port 9090 where dev-health-server runs (not 8080)
      port: 9090

    envs:
      # === Your Application Repository ===
      # Repository URL for sea-notes-saas-starter-kit
      - key: GITHUB_REPO_URL
        value: "https://github.com/bikramkgupta/sea-notes-saas-starter-kit"
        scope: RUN_TIME

      # For private repos, set your GitHub token (Personal Access Token with repo scope)
      # Leave empty for public repos
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET

      # Branch to sync - using hot-reload-dev branch
      - key: GITHUB_BRANCH
        value: "hot-reload-dev"
        scope: RUN_TIME

      # For monorepos: specify subfolder containing the application
      # The application code is in the "application" subdirectory
      - key: GITHUB_REPO_FOLDER
        value: "application"
        scope: RUN_TIME

      # === Application Startup ===
      # Command to start your app - uses dev_startup.sh from the application directory
      - key: DEV_START_COMMAND
        value: "bash dev_startup.sh"
        scope: RUN_TIME

      # === Sync Settings ===
      # How often to sync from GitHub (seconds)
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME

      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === Deploy Jobs (Optional) ===
      # Commands run on git commit change (e.g., "npm run db:migrate")
      # Leave empty for now - will configure later when database is added
      - key: PRE_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: PRE_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME
      - key: POST_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: POST_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME

      # === Application Environment Variables ===
      # Note: Database and other integrations will be configured later
      # For now, we'll let the app run without database connection
      # You can add these via DO Console after initial deployment:
      #   - AUTH_SECRET (required for NextAuth)
      #   - DATABASE_URL (will be configured after database setup)
      #   - Other variables as needed

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
