#
# DigitalOcean App Platform - Hot Reload Dev Environment
# Pre-built Node.js Image (Deploys in ~1 minute!)
#
# Usage:
#   doctl apps create --spec app-specs/app-nextjs.yaml
#
# After deployment, configure your app in the DO Console:
#   - Set GITHUB_REPO_URL to your repository (or keep ${GITHUB_REPO_URL} if deployed via GitHub Actions)
#   - Set GITHUB_TOKEN if private repo (as secret)
#   - Set DEV_START_COMMAND or add dev_startup.sh to your repo
#

name: my-nextjs-app
region: syd

services:
  - name: dev-workspace
    image:
      registry_type: GHCR
      registry: bikramkgupta
      repository: hot-reload-node
      tag: latest

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    http_port: 8080

    # Internal port for dev-health-server (keeps container alive for debugging)
    internal_ports:
      - 9090

    # CRITICAL: Health check on port 9090, NOT 8080
    # This ensures shell access even if your app crashes.
    health_check:
      http_path: /dev_health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      port: 9090

    envs:
      # === Your Repository ===
      - key: GITHUB_REPO_URL
        value: "${GITHUB_REPO_URL}"
        scope: RUN_TIME

      # For private repos, add your token here (or use envsubst)
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET

      # Branch to sync (leave empty for main/master)
      - key: GITHUB_BRANCH
        value: ""
        scope: RUN_TIME

      # === Startup Command ===
      # Uses dev_startup.sh which handles npm install automatically
      - key: DEV_START_COMMAND
        value: "bash dev_startup.sh"
        scope: RUN_TIME

      # If your app lives in a subfolder, set an explicit path:
      #   value: "bash application/dev_startup.sh"

      # === Sync Settings ===
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME
      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === Deploy Jobs ===
      # Leave PRE_DEPLOY empty - use dev_startup.sh for npm install
      # PRE_DEPLOY runs in strict mode and kills container on failure
      - key: PRE_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME

      # === Bindable variables (convenience) ===
      - key: BASE_URL
        value: "${APP_URL}"
        scope: RUN_TIME
      - key: APP_DOMAIN
        value: "${APP_DOMAIN}"
        scope: RUN_TIME
      - key: APP_ID
        value: "${APP_ID}"
        scope: RUN_TIME
      - key: COMMIT_HASH
        value: "${_self.COMMIT_HASH}"
        scope: RUN_TIME
      - key: PUBLIC_URL
        value: "${_self.PUBLIC_URL}"
        scope: RUN_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
