#
# DigitalOcean App Platform - Hot Reload Dev Environment
# Pre-built Full Image (Node.js + Python + Go)
# Deploys in ~1 minute!
#
# Usage:
#   doctl apps create --spec app-specs/app-full.yaml
#

name: hot-reload-dev
region: syd1

services:
  - name: dev-workspace
    image:
      registry_type: GHCR
      registry: bikramkgupta
      repository: hot-reload-full
      tag: latest

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    http_port: 8080

    # Internal port for dev-health-server (keeps container alive for debugging)
    internal_ports:
      - 9090

    # CRITICAL: Health check on port 9090 for shell access when app crashes
    health_check:
      http_path: /dev_health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      port: 9090

    envs:
      - key: GITHUB_REPO_URL
        value: ""
        scope: RUN_TIME
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_BRANCH
        value: ""
        scope: RUN_TIME
      - key: GITHUB_REPO_FOLDER
        value: ""
        scope: RUN_TIME
      - key: DEV_START_COMMAND
        value: ""
        scope: RUN_TIME
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME
      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === Deploy Jobs (Optional) ===
      # Commands run on git commit change
      - key: PRE_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: PRE_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME
      - key: POST_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: POST_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
