#
# DigitalOcean App Platform - Hot Reload Dev Environment
# Pre-built Python Image (Deploys in ~1 minute!)
#
# Usage:
#   doctl apps create --spec app-specs/app-python.yaml
#
# After deployment, configure your app in the DO Console:
#   - Set GITHUB_REPO_URL to your repository (or keep ${GITHUB_REPO_URL} if deployed via GitHub Actions)
#   - Set GITHUB_TOKEN if private repo (as secret)
#   - Set DEV_START_COMMAND or add dev_startup.sh to your repo
#

name: hot-reload-dev
region: syd

services:
  - name: dev-workspace
    # Pre-built image from GitHub Container Registry
    # No build phase = deploy in ~1 minute!
    image:
      registry_type: GHCR
      registry: bikramkgupta
      repository: hot-reload-python
      tag: latest

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb

    # Application port
    http_port: 8080

    # Internal port for dev-health-server (keeps container alive for debugging)
    internal_ports:
      - 9090

    # CRITICAL: Health check on port 9090 for shell access when app crashes
    health_check:
      http_path: /dev_health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      port: 9090

    envs:
      # === Your Application Repository ===
      - key: GITHUB_REPO_URL
        value: "${GITHUB_REPO_URL}"
        scope: RUN_TIME

      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET

      - key: GITHUB_BRANCH
        value: ""
        scope: RUN_TIME

      # === Application Startup ===
      # Examples for Python:
      #   - "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
      #   - "python -m flask run --host 0.0.0.0 --port 8080"
      #   - "bash dev_startup.sh"
      - key: DEV_START_COMMAND
        value: ""
        scope: RUN_TIME

      # If your app lives in a subfolder, set an explicit path:
      #   value: "bash application/dev_startup.sh"

      # === Sync Settings ===
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME

      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === Deploy Jobs (Optional) ===
      # Commands run on git commit change (e.g., "python manage.py migrate")
      - key: PRE_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: PRE_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME
      - key: POST_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: POST_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME

      # === Bindable variables (convenience) ===
      - key: BASE_URL
        value: "${APP_URL}"
        scope: RUN_TIME
      - key: APP_DOMAIN
        value: "${APP_DOMAIN}"
        scope: RUN_TIME
      - key: APP_ID
        value: "${APP_ID}"
        scope: RUN_TIME
      - key: COMMIT_HASH
        value: "${_self.COMMIT_HASH}"
        scope: RUN_TIME
      - key: PUBLIC_URL
        value: "${_self.PUBLIC_URL}"
        scope: RUN_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
