#
# DigitalOcean App Platform - Hot Reload Dev Environment
# Pre-built Go Image (Deploys in ~1 minute!)
#
# Usage:
#   doctl apps create --spec app-specs/app-go.yaml
#

name: hot-reload-dev
region: syd1

services:
  - name: dev-workspace
    image:
      registry_type: GHCR
      repository: bikramkgupta/hot-reload-go
      tag: latest

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 8080

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      port: 8080

    envs:
      - key: GITHUB_REPO_URL
        value: ""
        scope: RUN_TIME
      - key: GITHUB_TOKEN
        value: ""
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_BRANCH
        value: ""
        scope: RUN_TIME
      - key: GITHUB_REPO_FOLDER
        value: ""
        scope: RUN_TIME
      # Go examples:
      #   - "go run ."
      #   - "air" (for hot reload with air)
      #   - "bash dev_startup.sh"
      - key: DEV_START_COMMAND
        value: ""
        scope: RUN_TIME
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME
      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME
      - key: PRE_DEPLOY_FOLDER
        value: "scripts/pre-deploy"
        scope: RUN_TIME
      - key: PRE_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: PRE_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME
      - key: POST_DEPLOY_FOLDER
        value: "scripts/post-deploy"
        scope: RUN_TIME
      - key: POST_DEPLOY_COMMAND
        value: ""
        scope: RUN_TIME
      - key: POST_DEPLOY_TIMEOUT
        value: "300"
        scope: RUN_TIME

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
