#
# DigitalOcean App Platform - Hot Reload Dev Environment
#
# This spec is designed for use with GitHub Actions deployment.
# Variables like ${VAR_NAME} are substituted from GitHub Secrets.
#
# For manual deployment with doctl, use app.yaml in the root directory instead.
#

name: hot-reload-dev
region: syd1

services:
  - name: dev-workspace
    image:
      registry_type: GHCR
      registry: bikramkgupta
      repository: hot-reload-node
      tag: latest

    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb

    http_port: 8080

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
      port: 8080

    envs:
      # Repository to sync - automatically set by GitHub Actions
      - key: GITHUB_REPO_URL
        value: "${GITHUB_REPO_URL}"
        scope: RUN_TIME

      # For private repos - set APP_GITHUB_TOKEN in GitHub Secrets
      - key: GITHUB_TOKEN
        value: "${GITHUB_PAT}"
        scope: RUN_TIME
        type: SECRET

      # Branch to sync
      - key: GITHUB_BRANCH
        value: "${GITHUB_BRANCH}"
        scope: RUN_TIME

      # Subfolder for monorepos
      - key: GITHUB_REPO_FOLDER
        value: "${GITHUB_REPO_FOLDER}"
        scope: RUN_TIME

      # Startup command
      - key: DEV_START_COMMAND
        value: "${DEV_START_COMMAND}"
        scope: RUN_TIME

      # Sync interval
      - key: GITHUB_SYNC_INTERVAL
        value: "15"
        scope: RUN_TIME

      - key: WORKSPACE_PATH
        value: "/workspaces/app"
        scope: RUN_TIME

      # === App Secrets ===
      # Add your secrets to GitHub Secrets, then reference them here
      # The GitHub Action will substitute ${VAR_NAME} with the secret value

      - key: DATABASE_URL
        value: "${DATABASE_URL}"
        scope: RUN_TIME
        type: SECRET

      # Add more secrets as needed:
      # - key: API_KEY
      #   value: "${API_KEY}"
      #   scope: RUN_TIME
      #   type: SECRET

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
